services:
  app:
    container_name: app
    image: app
    restart: always
    networks:
      - main
    env_file:
      - ./.env
    ports:
      - '${PORT}:3000'

networks:
  main:
    external: true
